#!/bin/sh
set -eu

# env vars passed in via Docker:
# STARTUP_MAP
# GAME_MODE
# MUTATORS

UT_PATH="/ut-server"

die() {
  err_code="$1"; shift
  echo "$*" >&2
  exit "$err_code"
}

# IniSet borrowed from ASU
# args: {property group}  {property name} {property value} {ini file}
ini_set()
{
   TMP="/tmp/ut.ini.$$.tmp"
   INI="$4"

   awk 'BEGIN { eval ARGV[1]; eval ARGV[2]; eval ARGV[3]; instate = 0; done = 0; }
/^\[/ { if ((instate >= 1) && (done == 0)) { print item "=" value; done = 1; } if ($1 ~ "\\[" zone "\\]") { instate = 1; } else { instate = 0; } }
{
   if (instate == 2) {
      if (length($1) <= 1) {
         print item "=" value; print $0; done = 1;
      } else if ($1 ~ "^" item "=") {
         print item "=" value; instate = 0; done = 1;
      } else {
         print $0;
      }
   } else if (instate == 1) {
      print $0; instate = 2;
   } else {
      print $0;
   }
}
END { if (done == 0) { if (instate >= 1) { print item "=" value; } else { print "[" zone "]"; print item "=" value; print ""; } } }
' "zone=$1" "item=$2" "value=$3" < "$INI" > "$TMP"

   if [ $? -eq 0 ]; then
      mv "$TMP" "$INI"
   fi
}

create_symlink() {
  target="$1"
  relative_name="${target#*/.loki/ut/}"
  relative_dir=$(dirname "$relative_name")
  echo "LINK $target"

  if [ ! -e "${UT_PATH}/${relative_name}" ] && [ -e "${target}" ]; then
    echo "MKDIR ${UT_PATH}/${relative_dir}"
    mkdir -p "${UT_PATH}/${relative_dir}"
    ln -s "$target" "${UT_PATH}/${relative_name}"
  fi
}

# UT will not open native libraries (e.g. parts of ACE, if in use) from the preference directory.
# To work around this, on startup we symlink any dll/so from the preference dir into the main game.
# Additionally, some tools (also looking at ACE) do not work with resources in the preference directory
# (in this case, I am referring to UPackages), so an attempt is also made to link ACE specific files
# and all u/int files.
create_symlinks() {
  for file in /.loki/ut/System/*.u \
              /.loki/ut/System/*.int \
              /.loki/ut/System/*.so \
              /.loki/ut/System/*.dll \
              /.loki/ut/System/ACEFileList.txt \
              /.loki/ut/Logs \
              /.loki/ut/Shots \
              /.loki/ut/System/PlayerManager; do
    create_symlink "$file"
  done
}

launch_server() {
  UCC_CMD="${STARTUP_MAP}?game=$GAME_MODE"
  if [ -n "$MUTATORS" ]; then
    UCC_CMD="${UCC_CMD}?mutator=${MUTATORS}"
  fi

  # blanking HOME gets the ucc preference dir to be /.loki/ut
  HOME="" exec "${UT_PATH}/ucc" server "$UCC_CMD"
}

if [ "$#" -gt 0 ]; then
  while [ "$#" -gt 0 ]; do
    case "$1" in
      ini_set)
        [ "$#" -gt 4 ] || die 1 "Usage: $0 $1 FILE SECTION PROPERTY VALUE"
        ini_file="$2";shift
        ini_section="$2";shift
        ini_prop="$2";shift
        ini_val="$2";shift
        ini_set "$ini_section" "$ini_prop" "$ini_val" "$ini_file"
        ;;
      *)
        die 1 "wtf is $1"
    esac
    shift
  done
else
  create_symlinks
  launch_server
fi
